### ISSUE TITLE
Pose Graph Reduction through Trajectory Segmentation using Line Segments

### ISSUE THREAD

**Issue by wangshaojing** [ylatif/rrr#1]
Dear senior,   
I am deeply inspired by reading your paper（Go straight, Turn Right: Pose Graph Reduction through Trajectory Segmentation using Line Segments).  
Can you provide the source code and dataset for us to study and reference?
Thanks a lot ! 
Best wishes for you！

**Comment by ylatif** [comment]
Hi @wangshaojing 

Thank you for your interest in my work. The only think I could find in terms of the source code is a demo that I wrote for the paper (it was 7 years ago).

You can find the demo here : http://ylatif.github.io/confs/ECMR13/demo2/demo.html

The algorithm is implemented in javascript in this  [repo](https://github.com/ylatif/ylatif.github.io/tree/master/confs/ECMR13/demo2).

The function that implements the algorithm is [here](https://github.com/ylatif/ylatif.github.io/blob/ffc34304666a881e7fd58a31bcd006393fcdc6d6/confs/ECMR13/demo2/incrMergeSplit.js#L63)

Hope it helps,
Cheers

**Comment by wangshaojing** [comment]
Thanks!
I still have a question.
Are “full graph” and “original graph” the same? 
Their nodes are keyframes or frames?
